### ISSUE TITLE
add a prometheus custom config file

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-ansible#1]
In order to integrate geokrety/geokrety-website#300 we need to provide a prometheus config file wich embeds website scrape config in addition to default config

Example
````
global:
  scrape_interval:     ((prometheus_scrape_interval))s
  evaluation_interval: ((prometheus_evaluation_interval))s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'website'
    metrics_path: '/rest/internal/prometheus/metrics.php'
    scrape_interval: ((prometheus_website_scrape_interval))s
    static_configs:
    - targets: ['geokrety']
````

A working docker-compose file already exist for gkShell :
- compose file: [docker-compose.yml](https://github.com/geokrety/geokrety-website/blob/71e50315a3bee991e458c03cdc58adbd0f5fe9c7/gkShell/docker-compose.yml#L33)
- resources: [setup.sh](https://github.com/geokrety/geokrety-website/blob/feature/metrics/gkShell/config/prometheus/setup.sh) and [prometheus-template.yml](https://github.com/geokrety/geokrety-website/blob/feature/metrics/gkShell/config/prometheus/prometheus-template.yml)

---
Note that current default config (including push gateway) is:

````
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /prometheus/metrics
  scheme: http
  static_configs:
  - targets:
    - prometheus:9090
- job_name: pushgateway
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - pushgateway:9091
````
